language: cpp
env:
  global:
  - secure: dNf+ddgmbhuzrGHsO6eWuEQ9rTZbIQjdBX47TDnGulwWpOS8LyEoZNFz3IAvf9HJBY2L/pM3F6BvSfXpumX+qX2BVZLUETX54lk07i8PnGWgq0O0ylW5sB3xM0bNGPALiH3sBJEHeimEoRIAkbg+bXafLWo4cDFtQ7IT4mg6fQxq+MGNyr5GnSBkTRK7TdXef1dOylF0R2OV/xXVTr0xEkCb4ONB32ljZ1YZrYw0RzeDWX+rp674S1DnqhC3cYuOjK0Yl3h0uDHEI/rdvJmTahii9C5AILA8eB8Lc4jBlQmXlXYHy7Rr10KIwK7qYNFal6WyS4SbyBLZ6t3bNFrXe3ayMnhllVs0RsreMgMaJ78nGuHmpdQ8FJWlOIEWOYEFO6j/WnQwN7d6U4cgmB0mWmQJoO59qGuw1FsRTMssTJNeOd5t8WVi3AyNSV+GE4n+ZE1Bh4KIhmmhWno+w5iHKIHpr0SocxhPB5jQ2mEm1GhG8ZvM+wAollabkXCfeF9brGCh5IbTib10UpAkDkoeLYSpHO4Blshu5Tkpu0OXe1zcTwfUewbrZ1NZIS6LWdau6ISiPLQSnL+BwgZcIMJ/ZqUEmCtaBE79gQ/h730/Ekxkmdfr9KuvqnF+UTqXtRJeru/uZ0n2LTj7xrjpct2eFHZzGJlp2sAfQWfLK7EWg5A=


matrix:
  include:
    - os: linux
      dist: bionic
      env: BUILD_STATIC=true DEBUG=false ASAN=false
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
            - libmetis-dev
            - libnauty2-dev
    - os: linux
      dist: bionic
      env: BUILD_STATIC=false DEBUG=false ASAN=false
      addons:
        apt:
          packages:
            - gfortran
            - liblapack-dev
            - libmetis-dev
            - libnauty2-dev
    - os: linux
      dist: xenial
      env: BUILD_STATIC=true DEBUG=false ASAN=false
      addons:
        apt:
          packages:
            - gfortran
            - libgfortran-5-dev
            - liblapack-dev
            - libmetis-dev
            - libnauty2-dev
    - os: osx
      osx_image: xcode11
      env: OSX=10.14 CC=gcc CXX=g++ BUILD_STATIC=false DEBUG=false ASAN=false
      compiler: clang
    - os: osx
      osx_image: xcode11
      env: OSX=10.14  BUILD_STATIC=false DEBUG=false ASAN=false
      compiler: clang
    - os: osx
      osx_image: xcode10
      env: OSX=10.13  BUILD_STATIC=false DEBUG=false ASAN=false
      compiler: clang

  allow_failures:
    - os: windows

before_install:
- |-
    ############## Installing Additional Packages #################
    export PROJECT=$(basename $PWD)
    cd ..                      
    git clone https://github.com/coin-or/coinbrew
    bash coinbrew/.ci/install_packages.sh
    case $TRAVIS_OS_NAME in
      windows)
        BASH=bash
        alias make=mingw32-make  # so that Autotools can find it
        ;;
      osx)
        BASH=/usr/local/bin/bash
        ;;
      linux)
        BASH=bash
        ;;
    esac
    export BASH

before_script:
- |-
    ############# Fetching Dependencies ##############
    $BASH coinbrew/coinbrew fetch $PROJECT --no-prompt --skip-update

script:
- |-
    ############### Building Project ####################
    source coinbrew/.ci/setup_environment.sh
    ADD_CXXFLAGS="${ADD_CXXFLAGS} -fvisibility=hidden"
    $BASH coinbrew/coinbrew build $PROJECT "${COMMON_ARGS[@]}" "${ADD_ARGS[@]}" "${DBG_ARGS[@]}"

after_script:
- |-
    ############## Uploading BInaries ##################
    case $TRAVIS_OS_NAME in
      linux|osx)
        source coinbrew/.ci/setup_environment.sh
        $BASH coinbrew/.ci/upload_binaries.sh
        ;;
    esac
